#!/usr/bin/env python3
"""
Pinsker KL table (Theorem 2 of theory_appendix.tex).

Walks every recovery_radius_*.json in results/analysis/metrics/ and, for each
(method, seed) pair with both forget and retain-control data, emits:

    method, seed, eps_max, n_F, n_R, p_F, p_R, |p_F - p_R|, KL_LB (Pinsker)

Writes a Markdown table to results/analysis/reports/pinsker_kl_table.md and a
machine-readable JSON to results/analysis/metrics/pinsker_kl_table.json.

The valid direction is one-sided: rows with a positive forget-vs-retain gap
carry quantitative variational information about forget-set membership at the
audit scale. Near-zero gaps do not upper-bound leakage; any generic-fragility
reading must come from the measured equality and oracle/null controls, not from
Pinsker itself.
"""

import argparse
import glob
import json
import os
import re
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))

from src.theory.recovery_certification import JsonAnalyzer, pinsker_kl_lb, bretagnolle_huber_kl_lb


METRICS_DIR = "results/analysis/metrics"
REPORTS_DIR = "results/analysis/reports"

# Map raw suite names to short labels for the table.
_SUITE_LABEL = {
    "unlearn_kl_vit_cifar10_forget0": "Uniform-KL",
    "unlearn_ce_ascent_vit_cifar10_forget0": "CE-Asc",
    "unlearn_salun_vit_cifar10_forget0": "SalUn",
    "unlearn_scrub_distill_vit_cifar10_forget0": "SCRUB",
    "unlearn_scrub_vit_cifar10_forget0": "SCRUB",
    "unlearn_orbit_vit_cifar10_forget0": "ORBIT",
    "unlearn_rurk_vit_cifar10_forget0": "RURK",
    "unlearn_ceu_vit_cifar10_forget0": "CE-U",
    "unlearn_sga_vit_cifar10_forget0": "SGA",
    "unlearn_baldro_vit_cifar10_forget0": "BalDRO",
}


def _short(suite: str) -> str:
    return _SUITE_LABEL.get(suite, suite)


def collect(metrics_dir: str = METRICS_DIR):
    pattern = os.path.join(metrics_dir, "recovery_radius_*.json")
    paths = sorted(glob.glob(pattern))
    rows = []
    skipped = 0
    for p in paths:
        try:
            ja = JsonAnalyzer(p)
        except Exception as e:
            skipped += 1
            continue
        rows_from_file = ja.summarize()
        # Keep only rows with both forget and retain populated
        for row in rows_from_file:
            if row.n_retain == 0:
                continue
            # Pull a clean tag from the filename for traceability
            stem = os.path.basename(p).replace("recovery_radius_", "").replace(".json", "")
            rows.append({
                "file_stem": stem,
                "suite": row.suite,
                "label": _short(row.suite),
                "seed": row.seed,
                "eps_max": row.eps_max,
                "n_F": row.n_forget,
                "n_R": row.n_retain,
                "p_F": row.forget_p_at_eps,
                "p_R": row.retain_p_at_eps,
                "abs_gap": abs(row.forget_p_at_eps - row.retain_p_at_eps),
                "kl_lb_pinsker": pinsker_kl_lb(row.forget_p_at_eps, row.retain_p_at_eps),
                "kl_lb_bh": bretagnolle_huber_kl_lb(row.forget_p_at_eps, row.retain_p_at_eps),
            })
    return rows, skipped


def render_markdown(rows):
    # Sort by KL lower bound descending so the strongest selective-leakage rows
    # are at the top.
    rows = sorted(rows, key=lambda r: r["kl_lb_pinsker"], reverse=True)
    out = []
    out.append("# Pinsker Selective-Leakage Table\n")
    out.append("Generated by `scripts/analysis/30_pinsker_kl_table.py`. ")
    out.append("Theorem 2 of `results/analysis/figures/theory_appendix.tex`.\n\n")
    out.append("Each row is one (method, seed, audit-config). `p_F` is the empirical "
               "fraction of forget samples for which the audit recovered the forgotten "
               "class within `eps_max`; `p_R` is the same on matched retain controls. "
               "Pinsker's inequality forces "
               "`KL(Ber(p_F) || Ber(p_R)) >= 2 (p_F - p_R)^2`, the column `KL_LB(P)`. "
               "`KL_LB(BH)` is the tighter Bretagnolle-Huber bound.\n\n")
    out.append("| method | seed | eps_max | n_F | n_R | p_F | p_R | |Δ| | KL_LB(P) | KL_LB(BH) | file |\n")
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|\n")
    for r in rows:
        out.append(
            "| {label} | {seed} | {eps_max:.4f} | {n_F} | {n_R} | "
            "{p_F:.3f} | {p_R:.3f} | {abs_gap:.3f} | {kl_p:.4f} | {kl_bh:.4f} | `{fs}` |\n".format(
                label=r["label"], seed=r["seed"], eps_max=r["eps_max"],
                n_F=r["n_F"], n_R=r["n_R"],
                p_F=r["p_F"], p_R=r["p_R"], abs_gap=r["abs_gap"],
                kl_p=r["kl_lb_pinsker"], kl_bh=r["kl_lb_bh"], fs=r["file_stem"],
            )
        )
    out.append("\n## Reading guide\n\n")
    out.append("- **KL_LB ≈ 0**: the audit cannot distinguish forget from retain "
               "at this scale. The method may still be adversarially fragile, but "
               "any selective-leakage claim is empirically vacuous (Corollary 2.1).\n")
    out.append("- **KL_LB > 0**: the binary recoverability outcome carries at "
               "least this much variational information about forget-set membership. "
               "Selective leakage at scale `eps_max` is empirically certified at the "
               "rate shown.\n")
    out.append("- The Pinsker bound is loose near `p_F, p_R` close to 0 or 1; the "
               "Bretagnolle-Huber column is tighter there.\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--metrics-dir", default=METRICS_DIR)
    ap.add_argument("--out-md", default=os.path.join(REPORTS_DIR, "pinsker_kl_table.md"))
    ap.add_argument("--out-json", default=os.path.join(METRICS_DIR, "pinsker_kl_table.json"))
    args = ap.parse_args()

    rows, skipped = collect(args.metrics_dir)
    if not rows:
        print(f"No usable recovery_radius_*.json found under {args.metrics_dir} "
              f"(skipped {skipped} unreadable files).")
        return

    os.makedirs(os.path.dirname(args.out_md), exist_ok=True)
    os.makedirs(os.path.dirname(args.out_json), exist_ok=True)

    md = render_markdown(rows)
    with open(args.out_md, "w") as f:
        f.write(md)
    with open(args.out_json, "w") as f:
        json.dump({"rows": rows, "skipped_files": skipped}, f, indent=2)

    print(f"Wrote {len(rows)} rows (skipped {skipped} files) to:")
    print(f"  {args.out_md}")
    print(f"  {args.out_json}")
    # Show the top-5 by KL_LB
    rows_sorted = sorted(rows, key=lambda r: r["kl_lb_pinsker"], reverse=True)
    print("\nTop-5 selective-leakage rows by Pinsker KL_LB:")
    for r in rows_sorted[:5]:
        print(f"  {r['label']:8s} seed={r['seed']} p_F={r['p_F']:.3f} p_R={r['p_R']:.3f}  KL_LB={r['kl_lb_pinsker']:.4f}")


if __name__ == "__main__":
    main()
